name: C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Clang-format
        run: |
          find src include \( -name '*.cpp' -o -name '*.h' \) -print0 | \
          xargs -0 clang-format --dry-run --Werror

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake make g++ clang-tidy

      - name: Generate
        run: cmake -S . -B bin -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: cmake --build bin --parallel

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: bin
          if-no-files-found: error

  lint:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: bin

      - name: Clang-tidy
        run: |
          pwd
          ls -R
          find src include \( -name '*.cpp' -o -name '*.h' \) -print0 | \
          xargs -0 clang-tidy --use-color --header-filter='.*' -p bin

  test:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: bin

      - name: Show downloaded files
        run: find bin -maxdepth 3 -type f

      - name: Run tests
        run: |
          chmod +x bin/RayTracerTest
          ./bin/RayTracerTest